name: automate

on:
  schedule:
    - cron: '* * * * *'  # Ejecutar el script todos los días a las 00:00 UTC
    
jobs:
  ejecutar-script:
    name: Ejecutar script
    runs-on: ubuntu-latest

    steps:
    - name: Checkout del repositorio
      uses: actions/checkout@v4
      
    - name: Configurar Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10' 
        cache: 'pip'

    - name: Instalar dependencias
      run: |
        pip install requests
        pip install supabase
        pip install python-dotenv
    
    - name: revision de paquetes
      run: |
        pip list
        
    - name: Ejecutar script
      run: python script.py  # Reemplaza 'script.py' con el nombre de tu script
      env:
        CURRENCY_API_KEY: ${{ secrets.CURRENCY_API_KEY }}  # Asegúrate de que el nombre de la variable de entorno sea el correcto
        SUPABASE_URL: ${{ secrets.SUPABASEURL }}
        SUPABASE_KEY: ${{ secrets.SUPABASEKEY }}
